version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.0
